"""Aggregating a reporting period into the numbers a report shows.

Built on ``analytics_query`` rather than beside it. The report and the
analytics page must not be able to disagree about what a workspace's reach was
last month -- an agency that screenshots one and emails the other is the whole
point of the feature, and two implementations of "sum the reach" is how those
two numbers drift apart.

The period is resolved in the **workspace's** timezone and then fixed. A report
titled "September" covers September on the customer's calendar, not on the
server's, and it keeps covering it forever: the dates are stored on the row and
never recomputed.
"""

import logging
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta, timezone
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.account import Account
from app.models.report import ReportType
from app.services import analytics_query, campaign_analytics
from app.services.dashboard import DateRange, workspace_timezone

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class Period:
    """An inclusive span of local calendar days."""

    start: date
    end: date
    label: str

    @property
    def days(self) -> int:
        return (self.end - self.start).days + 1


def resolve_period(
    report_type: ReportType,
    *,
    account: Account,
    reference: Optional[date] = None,
    start: Optional[date] = None,
    end: Optional[date] = None,
) -> Period:
    """The calendar span a report of this type covers.

    Always the **last complete** period, not the one in progress: a "monthly"
    report generated on the 3rd that covers three days of the current month is
    a number nobody asked for, and it would change if regenerated.
    """
    tz = workspace_timezone(account)
    today = reference or datetime.now(tz).date()

    if report_type is ReportType.CUSTOM:
        if not start or not end:
            raise ValueError("A custom report needs both a start and an end date.")
        if end < start:
            raise ValueError("The end of the period cannot be before its start.")
        return Period(start, end, f"{start.isoformat()} to {end.isoformat()}")

    if report_type is ReportType.WEEKLY:
        # The most recent complete Monday-to-Sunday week.
        last_sunday = today - timedelta(days=today.weekday() + 1)
        monday = last_sunday - timedelta(days=6)
        return Period(monday, last_sunday, f"Week of {monday.strftime('%-d %B %Y')}")

    if report_type is ReportType.MONTHLY:
        first_of_this = today.replace(day=1)
        last_of_previous = first_of_this - timedelta(days=1)
        first_of_previous = last_of_previous.replace(day=1)
        return Period(
            first_of_previous, last_of_previous,
            last_of_previous.strftime("%B %Y"),
        )

    # QUARTERLY
    quarter = (today.month - 1) // 3
    first_of_this_quarter = date(today.year, quarter * 3 + 1, 1)
    last_of_previous = first_of_this_quarter - timedelta(days=1)
    start_month = (last_of_previous.month - 1) // 3 * 3 + 1
    first_of_previous = date(last_of_previous.year, start_month, 1)
    label = f"Q{(start_month - 1) // 3 + 1} {first_of_previous.year}"
    return Period(first_of_previous, last_of_previous, label)


def to_range(period: Period, account: Account) -> DateRange:
    """The analytics window for a period.

    Half-open in UTC, because that is what ``analytics_query`` speaks, built
    from local midnight to local midnight-after-the-end so the last day is
    included whole.
    """
    tz = workspace_timezone(account)
    start = datetime.combine(period.start, time.min, tzinfo=tz).astimezone(timezone.utc)
    end = datetime.combine(
        period.end + timedelta(days=1), time.min, tzinfo=tz
    ).astimezone(timezone.utc)
    return DateRange(
        start=start, end=end, label=period.label, timezone_name=tz.key
    )


def _pct(value: Optional[float]) -> Optional[float]:
    return None if value is None else round(value, 1)


def _executive_summary(payload: dict) -> str:
    """One paragraph a human can paste into an email.

    Written from the numbers rather than generated by a model: a report is a
    statement of fact, and a sentence that sometimes hallucinates a trend is
    worse than no sentence. Every clause here is conditional on the underlying
    figure actually existing.
    """
    metrics = payload["metrics"]
    parts: list[str] = []

    posts = payload["content"]["published_posts"]
    parts.append(
        f"{posts} post{'s' if posts != 1 else ''} published across "
        f"{len(payload['platforms'])} platform"
        f"{'s' if len(payload['platforms']) != 1 else ''}"
        if posts
        else "No posts were published in this period"
    )

    reach = metrics.get("reach", {}).get("value")
    if reach:
        change = metrics["reach"].get("change_percent")
        movement = (
            f", {'up' if change >= 0 else 'down'} {abs(change):.1f}% on the "
            "previous period" if change is not None else ""
        )
        parts.append(f"reaching {reach:,} accounts{movement}")

    followers = payload["audience"]["current"]
    growth = payload["audience"]["change"]
    if followers is not None:
        if growth:
            parts.append(
                f"Audience {'grew' if growth > 0 else 'fell'} by {abs(growth):,} to "
                f"{followers:,}"
            )
        else:
            parts.append(f"Audience held at {followers:,}")

    rate = metrics.get("engagement_rate", {}).get("value")
    if rate is not None:
        parts.append(f"Engagement rate was {rate:.2f}%")

    return ". ".join(parts) + "."


def _campaign_executive_summary(payload: dict, campaign_name: str) -> str:
    """The campaign equivalent of :func:`_executive_summary`.

    A separate function rather than a branch inside that one because the two
    describe different things. This one never mentions audience growth: a
    campaign cannot be credited with follower movement (see
    :mod:`app.services.campaign_analytics`), and a summary that quietly
    borrowed the workspace's figure would be attributing it.
    """
    totals = payload["metrics"]
    progress = payload["campaign"]["progress"]
    parts: list[str] = [f"“{campaign_name}”"]

    published = progress["posts_published"]
    platform_count = len(payload["platforms"])
    if published:
        parts.append(
            f"published {published} post{'s' if published != 1 else ''} across "
            f"{platform_count} platform{'s' if platform_count != 1 else ''}"
        )
    else:
        parts.append("published no posts in this period")

    reach = totals.get("reach", {}).get("value")
    if reach:
        parts.append(f"reaching {reach:,} accounts")

    rate = totals.get("engagement_rate", {}).get("value")
    if rate is not None:
        parts.append(f"at a {rate:.2f}% engagement rate")

    summary = " ".join(parts) + "."

    if progress["on_track"] is not None:
        summary += (
            " The campaign is ahead of its posting schedule."
            if progress["on_track"]
            else " The campaign is behind its posting schedule."
        )
    return summary


async def aggregate_campaign(
    db: AsyncSession, account: Account, period: Period, campaign
) -> dict:
    """A report payload scoped to one campaign.

    Deliberately narrower than :func:`aggregate`. A campaign report carries the
    performance of its own posts and nothing else: ``analytics_daily`` has no
    campaign dimension, so account reach, follower counts and audience
    demographics cannot be attributed to a campaign and are absent rather than
    approximated. ``not_attributable`` says so in the payload, and the renderers
    read every optional section with ``.get``, so the sections simply do not
    appear.

    The metrics dict keeps the ``{value, previous, change, change_percent}``
    shape the renderers expect, with ``previous`` null throughout: the window
    before a campaign is not a comparable period, and inventing one would put a
    meaningless arrow on a client's PDF.
    """
    window = to_range(period, account)
    data = await campaign_analytics.dashboard(
        db, account, campaign, window=window, top_limit=10
    )

    totals = data["totals"]
    metrics = {
        name: {"value": totals.get(name), "previous": None,
                "change": None, "change_percent": None}
        for name in ("reach", "impressions", "clicks", "video_views",
                     "likes", "comments", "shares", "saves", "engagement")
    }
    metrics["engagement_rate"] = {
        "value": totals.get("engagement_rate"), "previous": None,
        "change": None, "change_percent": None,
    }

    payload = {
        "workspace": {"id": str(account.id), "name": account.name},
        "campaign": {
            **data["campaign"],
            "progress": data["progress"],
            "budget": data["budget"],
        },
        "period": {
            "start": period.start.isoformat(),
            "end": period.end.isoformat(),
            "days": period.days,
            "label": period.label,
            "timezone": window.timezone_name,
        },
        "metrics": metrics,
        "has_data": any(
            totals.get(name) for name in ("reach", "impressions", "engagement")
        ),
        "platforms": data["platforms"],
        "top_posts": data["top_posts"],
        "content": {
            "published_posts": data["progress"]["posts_published"],
            "total_interactions": totals.get("engagement"),
        },
        "not_attributable": data["not_attributable"],
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    payload["executive_summary"] = _campaign_executive_summary(
        payload, data["campaign"]["name"]
    )
    return payload


async def aggregate(db: AsyncSession, account: Account, period: Period) -> dict:
    """Everything a report shows, in one payload.

    Shared with the analytics endpoints, so a figure here is the same figure
    the customer already saw on the dashboard.
    """
    window = to_range(period, account)

    overview = await analytics_query.overview(db, account, window)
    platforms = await analytics_query.platforms(db, account, window)
    top_posts = await analytics_query.posts(
        db, account, window, sort="engagement", order="desc", limit=10
    )
    audience = await analytics_query.audience(db, account, window)

    interactions = sum(
        (overview["metrics"].get(name, {}).get("value") or 0)
        for name in ("likes", "comments", "shares", "saves")
    )

    payload = {
        "workspace": {"id": str(account.id), "name": account.name},
        "period": {
            "start": period.start.isoformat(),
            "end": period.end.isoformat(),
            "days": period.days,
            "label": period.label,
            "timezone": window.timezone_name,
        },
        "compared_to": overview["compared_to"],
        "metrics": overview["metrics"],
        "has_data": overview["has_data"],
        "audience": audience,
        "platforms": platforms,
        "top_posts": top_posts,
        "content": {
            "published_posts": len(top_posts),
            "total_interactions": interactions,
        },
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    payload["executive_summary"] = _executive_summary(payload)
    return payload


# ---------------------------------------------------------------------------
# Branding
# ---------------------------------------------------------------------------

DEFAULT_BRANDING = {
    "company_name": "MarketEngine",
    "primary_color": "#6d5ef6",
    "accent_color": "#10b981",
    "logo_url": None,
    "footer_note": None,
}

# Anything outside this is dropped rather than rendered. The branding dict
# reaches an HTML template, so an unbounded blob here would be a way to put
# arbitrary markup into a PDF the workspace's clients receive.
ALLOWED_BRANDING_KEYS = frozenset(DEFAULT_BRANDING)


def sanitise_branding(raw: Optional[dict], *, entitled: bool) -> dict:
    """The branding to render with.

    Without the ``white_label`` entitlement the customer's own branding is
    ignored and the product's defaults are used -- not an error, because a
    report is still worth having, and a hard failure on the plan boundary would
    mean a scheduled report silently stops arriving the month a plan changes.
    """
    branding = dict(DEFAULT_BRANDING)
    if not entitled or not raw:
        return branding

    for key in ALLOWED_BRANDING_KEYS:
        value = raw.get(key)
        if value is None:
            continue
        if key.endswith("_color"):
            text = str(value).strip()
            # Only a hex literal reaches the stylesheet.
            if len(text) in (4, 7) and text.startswith("#") and all(
                ch in "0123456789abcdefABCDEF" for ch in text[1:]
            ):
                branding[key] = text
        elif key == "logo_url":
            text = str(value).strip()
            if text.startswith(("https://", "http://")):
                branding[key] = text
        else:
            branding[key] = str(value)[:120]
    return branding
