"""recurring schedules and queue slots

Revision ID: 05f927d466f3
Revises: ddf239296d4b
Create Date: 2026-09-08 20:49:57.819642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '05f927d466f3'
down_revision: Union[str, Sequence[str], None] = 'ddf239296d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Created explicitly, then referenced with create_type=False.
#
# op.create_table fires the enum's before_create with checkfirst=False and
# memoises it for the life of the Alembic process, so a fresh run passes and a
# downgrade-then-upgrade in the same process raises DuplicateObjectError. Only
# postgresql.ENUM honours create_type; sa.Enum ignores it silently.
_STATUS_ENUM = postgresql.ENUM(
    "ACTIVE", "PAUSED", "COMPLETED", "CANCELLED",
    name="recurrence_status_enum",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _STATUS_ENUM.create(bind, checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('time_local', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'weekday', 'time_local', name='uq_queue_slot')
    )
    op.create_index('ix_queue_slots_account', 'queue_slots', ['account_id', 'is_active'], unique=False)
    op.create_table('recurring_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('template_post_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('rrule', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('starts_at_local', sa.DateTime(), nullable=False),
    sa.Column('until_local', sa.DateTime(), nullable=True),
    sa.Column('max_occurrences', sa.Integer(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('status', _STATUS_ENUM, nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_schedules_account', 'recurring_schedules', ['account_id'], unique=False)
    op.create_index('ix_recurring_schedules_due', 'recurring_schedules', ['status', 'next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recurring_schedules_due', table_name='recurring_schedules')
    op.drop_index('ix_recurring_schedules_account', table_name='recurring_schedules')
    op.drop_table('recurring_schedules')
    op.drop_index('ix_queue_slots_account', table_name='queue_slots')
    op.drop_table('queue_slots')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _STATUS_ENUM.drop(bind, checkfirst=True)
