"""inbox

Revision ID: 3e7835da8a96
Revises: c2b59efdbdb6
Create Date: 2026-09-09 01:02:57.347186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e7835da8a96'
down_revision: Union[str, Sequence[str], None] = 'c2b59efdbdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Created explicitly, referenced with create_type=False. op.create_table fires
# an enum's before_create with checkfirst=False and memoises it per Alembic
# process, so a downgrade-then-upgrade in one process raises
# DuplicateObjectError. Only postgresql.ENUM honours create_type.
_TYPE_ENUM = postgresql.ENUM(
    "COMMENT", "DM", "MENTION", name="inbox_thread_type_enum", create_type=False)
_STATUS_ENUM = postgresql.ENUM(
    "OPEN", "RESOLVED", name="inbox_thread_status_enum", create_type=False)
_DIRECTION_ENUM = postgresql.ENUM(
    "INBOUND", "OUTBOUND", "INTERNAL",
    name="inbox_message_direction_enum", create_type=False)
_ENUMS = (_TYPE_ENUM, _STATUS_ENUM, _DIRECTION_ENUM)


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum in _ENUMS:
            enum.create(bind, checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('type', _TYPE_ENUM, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('parent_external_id', sa.String(length=255), nullable=True),
    sa.Column('participant', sa.String(length=200), nullable=False),
    sa.Column('participant_handle', sa.String(length=200), nullable=True),
    sa.Column('permalink', sa.String(length=1000), nullable=True),
    sa.Column('status', _STATUS_ENUM, nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=280), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_account_id', 'external_id', name='uq_inbox_thread_external')
    )
    op.create_index('ix_inbox_threads_account_activity', 'inbox_threads', ['account_id', 'last_message_at'], unique=False)
    op.create_index('ix_inbox_threads_assignee', 'inbox_threads', ['assigned_to'], unique=False)
    op.create_index('ix_inbox_threads_status', 'inbox_threads', ['account_id', 'status'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('direction', _DIRECTION_ENUM, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('author_handle', sa.String(length=200), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['inbox_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'external_id', name='uq_inbox_message_external')
    )
    op.create_index('ix_inbox_messages_thread_time', 'inbox_messages', ['thread_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inbox_messages_thread_time', table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index('ix_inbox_threads_status', table_name='inbox_threads')
    op.drop_index('ix_inbox_threads_assignee', table_name='inbox_threads')
    op.drop_index('ix_inbox_threads_account_activity', table_name='inbox_threads')
    op.drop_table('inbox_threads')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum in _ENUMS:
            enum.drop(bind, checkfirst=True)
