"""review workflow

Adds the review states, the comment thread, and post assignment.

Three enum labels are added to post_status_enum: IN_REVIEW,
CHANGES_REQUESTED and CLIENT_REVIEW. Alembic's autogenerate does not detect
enum value additions, so these are written by hand -- a migration that only
carried the autogenerated table and columns would deploy and then fail at the
first attempt to write one of the new statuses.

Two Postgres constraints shape how it is done:

* ``ALTER TYPE ... ADD VALUE`` cannot be used in the *same transaction* that
  adds it. The backfill below therefore runs after an explicit COMMIT.
* An enum label cannot be dropped. ``PENDING_APPROVAL`` is superseded by
  ``IN_REVIEW`` and its rows are migrated, but the label itself has to stay --
  so the model keeps it declared, marked legacy, and nothing writes it.

Revision ID: 473557f3ff15
Revises: 5f51a51491fe
Create Date: 2026-09-08 10:54:24.516209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '473557f3ff15'
down_revision: Union[str, Sequence[str], None] = '5f51a51491fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The states the workflow adds. IN_REVIEW replaces PENDING_APPROVAL, which
# cannot be removed from the type.
NEW_STATUSES = ("IN_REVIEW", "CHANGES_REQUESTED", "CLIENT_REVIEW")


def upgrade() -> None:
    # Postgres stores enum *member names*, so these are the uppercase Python
    # names, not the lowercase values.
    for label in NEW_STATUSES:
        op.execute(
            f"ALTER TYPE post_status_enum ADD VALUE IF NOT EXISTS '{label}'"
        )
    # A label added in this transaction cannot be used in it. Commit before the
    # backfill, or the UPDATE below fails with "unsafe use of new value".
    op.execute("COMMIT")
    op.execute(
        "UPDATE posts SET status = 'IN_REVIEW' WHERE status = 'PENDING_APPROVAL'"
    )

    op.create_table('post_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_deleted_at'), 'post_comments', ['deleted_at'], unique=False)
    op.create_index('ix_post_comments_post_created', 'post_comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_posts_assigned_to'), 'posts', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['assigned_to'], ['id'])


def downgrade() -> None:
    # Rows move back to the label that still exists. The three added labels
    # stay in the type: Postgres cannot drop an enum value, and recreating the
    # type would mean rewriting every posts row and every dependent view.
    op.execute(
        "UPDATE posts SET status = 'PENDING_APPROVAL' "
        "WHERE status IN ('IN_REVIEW', 'CHANGES_REQUESTED', 'CLIENT_REVIEW')"
    )

    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_assigned_to'), table_name='posts')
    op.drop_column('posts', 'due_at')
    op.drop_column('posts', 'assigned_to')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index('ix_post_comments_post_created', table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_deleted_at'), table_name='post_comments')
    op.drop_table('post_comments')
