"""reports

Revision ID: c2b59efdbdb6
Revises: 05f927d466f3
Create Date: 2026-09-08 23:42:38.833515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2b59efdbdb6'
down_revision: Union[str, Sequence[str], None] = '05f927d466f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Created explicitly, referenced with create_type=False.
#
# op.create_table fires an enum's before_create with checkfirst=False and
# memoises it per Alembic process: a fresh run passes, a downgrade-then-upgrade
# in the same process raises DuplicateObjectError. Only postgresql.ENUM honours
# create_type; sa.Enum ignores it silently.
_TYPE_ENUM = postgresql.ENUM(
    "WEEKLY", "MONTHLY", "QUARTERLY", "CUSTOM",
    name="report_type_enum", create_type=False,
)
_STATUS_ENUM = postgresql.ENUM(
    "PENDING", "GENERATING", "READY", "FAILED",
    name="report_status_enum", create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _TYPE_ENUM.create(bind, checkfirst=True)
        _STATUS_ENUM.create(bind, checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('type', _TYPE_ENUM, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', _STATUS_ENUM, nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('file_keys', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_account_created', 'reports', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_reports_period', 'reports', ['account_id', 'type', 'period_start'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_period', table_name='reports')
    op.drop_index('ix_reports_account_created', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _TYPE_ENUM.drop(bind, checkfirst=True)
        _STATUS_ENUM.drop(bind, checkfirst=True)
