"""subscription_events and api_errors

Revision ID: ddf239296d4b
Revises: cb6c84de6491
Create Date: 2026-09-08 19:59:41.974225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ddf239296d4b'
down_revision: Union[str, Sequence[str], None] = 'cb6c84de6491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The type is created once, explicitly, and referenced with create_type=False
# everywhere else.
#
# ``op.create_table`` fires the enum's ``before_create`` with checkfirst=False
# and memoises that it has done so for the life of the Alembic process. A fresh
# run therefore passes and a downgrade-then-upgrade in the same process raises
# DuplicateObjectError. Only ``postgresql.ENUM`` honours create_type; the
# generic ``sa.Enum`` silently ignores it.
_SOURCE_ENUM = postgresql.ENUM(
    "CHECKOUT", "WEBHOOK", "ADMIN", "SYSTEM",
    name="subscription_event_source_enum",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _SOURCE_ENUM.create(bind, checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('exception_class', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_errors_class_created', 'api_errors', ['exception_class', 'created_at'], unique=False)
    op.create_index('ix_api_errors_created', 'api_errors', ['created_at'], unique=False)
    op.create_index('ix_api_errors_path_created', 'api_errors', ['path', 'created_at'], unique=False)
    op.create_table('subscription_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('from_tier', sa.String(length=50), nullable=True),
    sa.Column('to_tier', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('mrr_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', _SOURCE_ENUM, nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_events_created', 'subscription_events', ['created_at'], unique=False)
    op.create_index('ix_subscription_events_org_created', 'subscription_events', ['organization_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscription_events_org_created', table_name='subscription_events')
    op.drop_index('ix_subscription_events_created', table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index('ix_api_errors_path_created', table_name='api_errors')
    op.drop_index('ix_api_errors_created', table_name='api_errors')
    op.drop_index('ix_api_errors_class_created', table_name='api_errors')
    op.drop_table('api_errors')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _SOURCE_ENUM.drop(bind, checkfirst=True)
